nelmio_api_doc:
    documentation:
        info:
            title: Todo Tasks Api
            description: https://github.com/ArtemDidyk-Dev/todo-api
            version: 1.0.0
    areas: # to filter documented areas
        default:
            disable_default_routes: true
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
