networks:
  todo-network:
    name: todo-network

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
    volumes:
      - /opt/docker/todo/mysql:/var/lib/mysql:delegated
    networks:
      - todo-network
    ports:
      - "8952:3306"
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todo-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: todo
      PMA_PASSWORD: todo
      PMA_ABSOLUTE_URI: http://localhost:8080/
    ports:
      - "8090:80"
    networks:
      - todo-network
    depends_on:
      - mysql