networks:
  todo-network:
    name: todo-network
    external: true

services:
  php:
    container_name: todo-php
    env_file:
      - .env
    networks:
      - todo-network
    restart: unless-stopped

  caddy:
    container_name: caddy
    depends_on:
      - php
    ports:
      - "8950:80"
    networks:
      - todo-network
    restart: unless-stopped
