openapi: 3.0.0
info:
  title: Todo API
  description: API (todo)
  version: 0.0.1
servers:
  - url: http://localhost:8950/api
paths:
  /v1/tasks:
    $ref: './paths/tasks.yaml'
  /v1/task/{id}:
    $ref: './paths/task.yaml'
  /v1/passphrase:
    $ref: './paths/passphrase.yaml'
